import { beforeEach, describe, expect, it, vi } from "vitest";

const generateContent = vi.fn();

// Fix: explicitly use mockImplementation for constructor behavior
vi.mock("@google/genai", () => {
  return {
    GoogleGenAI: vi.fn().mockImplementation(function() {
      return {
        models: { generateContent },
      };
    }),
  };
});

describe("ai.service", () => {
  beforeEach(() => {
    // Fix: Remove vi.resetModules() from here to keep module state clean across test sweeps
    vi.clearAllMocks();
    
    // Set default envs before importing
    process.env.AI_PROVIDER = "gemini-test-model";
    process.env.AI_KEY = "test-key";
  });

  it("returns the text generated by the configured AI model", async () => {

    process.env.AI_KEY = "test-key";
    generateContent.mockResolvedValue({ text: '{"summary":"Short summary"}' });

    const { generateSummary } = await import("../../../../src/objective1/services/ai.service.js");
    const result = await generateSummary("Long medical note");

    expect(result).toBe('{"summary":"Short summary"}');
    expect(generateContent).toHaveBeenCalledWith(expect.objectContaining({
      model: "gemini-test-model",
      contents: "Long medical note",
    }));
  });

  it("rejects when AI configuration is missing", async () => {
    // Mutate the env directly before pulling the fresh check
    process.env.AI_KEY = ""; 

    const { generateSummary } = await import("../../../../src/objective1/services/ai.service.js");

    await expect(generateSummary("A prompt")).rejects.toThrow(
      "AI provider or API key is not configured."
    );

    expect(generateContent).not.toHaveBeenCalled();
  });

  it("hides provider failures behind a service-safe error", async () => {
    generateContent.mockRejectedValue(new Error("Provider unavailable"));
    const errorSpy = vi.spyOn(console, "error").mockImplementation(() => {});

    const { generateSummary } = await import("../../../../src/objective1/services/ai.service.js");

    await expect(generateSummary("A prompt")).rejects.toThrow(
      "Unable to generate summary at this time."
    );

    errorSpy.mockRestore();
  });
});