import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("../../../../src/objective1/services/ai.service.js", () => ({
  generateSummary: vi.fn(),
}));

import { generateSummary } from "../../../../src/objective1/services/ai.service.js";
import { generateSummaryService } from "../../../../src/objective1/services/summary.service.js";

describe("summary.service", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("returns the summary generated by the AI service", async () => {
    generateSummary.mockResolvedValue('{"summary":"Short summary"}');

    await expect(generateSummaryService("Long note")).resolves.toBe(
      '{"summary":"Short summary"}'
    );
    expect(generateSummary).toHaveBeenCalledWith("Long note");
  });

  it("returns a stable error when the AI service fails", async () => {
    generateSummary.mockRejectedValue(new Error("Provider unavailable"));
    const errorSpy = vi.spyOn(console, "error").mockImplementation(() => {});

    await expect(generateSummaryService("Long note")).rejects.toThrow(
      "Summary service is temporarily unavailable."
    );

    errorSpy.mockRestore();
  });
});
